name: 🐞 Bug report
description: Report an issue that should be fixed
labels: [triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. It helps make our project better.

        Please try to include as much information as possible.
  - type: input
    attributes:
      label: What version of the project are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: What do you see instead?
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
